openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://localhost:8080
tags:
  - name: micarrito-api-credentials
    description: Session management for MiCarrito App
paths:
  /login:
    post:
      tags:
        - micarrito-api-credentials
      summary: Logs user into the system
      description: ''
      operationId: loginUser
      parameters:
        - name: email
          in: query
          description: The user email for login
          required: true
          schema:
            type: string
        - name: password
          in: query
          description: The password for login in clear text
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation returns sessionID
          content:
            application/json:
              schema:
                type: string
                example: 1ad45f52-7ec8-11ee-b962-0242ac120002


        '400':
          description: Invalid username/password supplied
  /logout:
    post:
      tags:
        - micarrito-api-credentials
      summary: Logs out current logged in user session
      description: ''
      operationId: logoutUser
      parameters: []
      responses:
        default:
          description: successful operation
  /session:
    get:
      tags:
        - micarrito-api-credentials
      summary: Get session of current user
      description: ''
      operationId: getUserByName
      parameters:
        - name: session_id
          in: cookie
          description: 'The sessionId of the current user'
          required: true
          schema:
            type: string
            example: 1ad45f52-7ec8-11ee-b962-0242ac120002

      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
        '400':
          description: Invalid sessionId supplied
        '404':
          description: Session not found
components:
  schemas:
    Session:
      type: object
      properties:
        id:
          type: string
          example: 1ad45f52-7ec8-11ee-b962-0242ac120002

        id_usuario:
          type: integer
          format: int64
          example: 10
        status:
          type: string
          enum:
            - active
            - expired
            - blocked
          description: Session Status
          example: active
      xml:
        name: session